// AUTO-EXTRACTED byte-identical snapshots from dist/index.html.
// If any chunk stops matching dist, tests/test_detect.cjs fails — re-extract after editing the detectors.
module.exports = {
  local: "var Yv=EN9u=>EN9u;",
  distChunks: [
    "function Ii(t){if(typeof t==\"number\")return isFinite(t)?t:null;if(t==null||t===\"\")return null;let e=String(t).trim().replace(/[\\s\\u00A0']/g,\"\"),i=/^\\(.*\\)$/.test(e)||/CR$/i.test(e)||/-$/.test(e.replace(/[^0-9.,\\-]/g,\"\"));if(e=e.replace(/(CR|DR)$/i,\"\"),e=e.replace(/[()]/g,\"\").replace(/[^0-9.,\\-]/g,\"\").replace(/-+$/,\"\"),!e||!/[0-9]/.test(e))return null;e.includes(\",\")&&e.includes(\".\")?e=e.lastIndexOf(\",\")>e.lastIndexOf(\".\")?e.replace(/\\./g,\"\").replace(\",\",\".\"):e.replace(/,/g,\"\"):(e.match(/,/g)||[]).length===1&&/,\\d{1,2}$/.test(e)?e=e.replace(\",\",\".\"):!e.includes(\",\")&&(e.match(/\\./g)||[]).length>1?e=e.replace(/\\./g,\"\"):e=e.replace(/,/g,\"\");let s=parseFloat(e);return isFinite(s)?i?-s:s:null}",
    "var Oa=t=>{let e=String(t).trim();if(!e)return null;/*EN9NUMSLASH*/if(/\\d\\s*[/:]\\s*\\d/.test(e))return null;if(/^\\(?\\s*-?[\\d.,\\s ']+\\s*\\)?\\s*(?:CR|DR)?\\s*\\/?\\s*$/i.test(e)&&/\\d/.test(e))return Ii(e);let i=/[A-Za-z\\u00C0-\\u024F\\u0600-\\u06FF\\u4E00-\\u9FFF]/.test(e),s=Ii(e);return s!==null&&!i?s:null},$w=t=>/[A-Za-z\\u00C0-\\u024F\\u0600-\\u06FF\\u4E00-\\u9FFF]/.test(String(t))&&Oa(String(t))===null",
    "/*EN9CCYTOK-BEGIN*/var EN9ccySet=null,EN9ccyTok=function(m){if(EN9ccySet===null){try{EN9ccySet=new Set(Object.keys(Pa))}catch(e){EN9ccySet=new Set()}}return EN9ccySet.has(m.toUpperCase())?\" \":m};/*EN9CCYTOK-END*/var EN9_CLP=t=>t>=1990&&t<=2035?t:null,EN9_CYW=/^(current\\s+(financial\\s+)?year|this\\s+year|cy)$/i,EN9_PYW=/^((prior|previous|last)\\s+(financial\\s+)?year|py)$/i,EN9_HY=t=>{let e=String(t??\"\").trim(),i;if(/^(19|20)\\d{2}$/.test(e))return parseInt(e,10);if(i=/^fy\\s*'?((19|20)\\d{2})$/i.exec(e))return EN9_CLP(parseInt(i[1],10));if(i=/^fy\\s*'?(\\d{2})$/i.exec(e))return EN9_CLP(2e3+parseInt(i[1],10));if(e.length>30||/[.,]\\d{2}$/.test(e))return null;if(Oa(e)!==null&&/[()\\-]|CR|DR/i.test(e))return null;let s=[...e.matchAll(/(?:19|20)\\d{2}/g)].filter(a=>{let A=e[a.index-1],r=e[a.index+4];return!(A>=\"0\"&&A<=\"9\")&&!(r>=\"0\"&&r<=\"9\")});if(s.length!==1)return null;let n=(e.slice(0,s[0].index)+e.slice(s[0].index+4)).replace(/\\b(year|years|yr|period|ended|ending|end|as|at|on|of|for|the|to)\\b/gi,\" \").replace(/\\b(jan(uary)?|feb(ruary)?|mar(ch)?|apr(il)?|may|jun(e)?|jul(y)?|aug(ust)?|sep(t(ember)?)?|oct(ober)?|nov(ember)?|dec(ember)?)\\b/gi,\" \").replace(/'0{3}s?|\\b000s?\\b/gi,\" \").replace(/\\b[A-Za-z]{3}\\b/g,EN9ccyTok).replace(/\\b\\d{1,2}(st|nd|rd|th)?\\b/gi,\" \").replace(/[\\s.,\\/\\-\u2013\u2014:;()'\"$\u20ac\u00a3\u00a5\u20b9]+/g,\"\");return n===\"\"?EN9_CLP(parseInt(s[0][0],10)):null},EN9_RSV=(t,e)=>t.map(i=>i.cols.some(s=>s.year<0)?e&&e.cy?{...i,cols:i.cols.map(s=>({...s,year:s.year===-1?e.cy:s.year===-2?e.py??e.cy-1:s.year}))}:null:i).filter(Boolean),EN9_INH=(t,e)=>{let i=new Map,s=new Set(t.map(A=>A.page)),n=[...e].sort((A,r)=>A-r),a=null;for(let A of n)s.has(A)?a=A:a!==null&&A-a<=3&&i.set(A,a);return i};",
    "function oJ(t){for(let e of t.slice(0,10)){if(!e)continue;let i=e.map((a,A)=>({c:String(a??\"\").trim(),i:A})).filter(a=>a.c!==\"\");if(!i.length)continue;let s=[],EN9w=[],n=[];for(let a of i){let A=/^(19|20)\\d{2}$/.test(a.c)?parseInt(a.c,10):null,r=A!==null?A:EN9_HY(a.c);A!==null?s.push({y:A,i:a.i,b:1}):r!==null?s.push({y:r,i:a.i,b:0}):EN9_CYW.test(a.c)?EN9w.push({y:-1,i:a.i}):EN9_PYW.test(a.c)?EN9w.push({y:-2,i:a.i}):n.push(a)}let EN9g=n.every(a=>a.c.length<=14)&&n.length<=1;if(s.length>=1&&s.length<=4&&!EN9w.length&&EN9g&&(s.every(a=>a.b)||s.length>=2)){let a=[];for(let A of s)a[A.i]=A.y;return a}if(!s.length&&EN9w.length===2&&EN9w.some(a=>a.y===-1)&&EN9w.some(a=>a.y===-2)&&EN9g&&n.every(a=>Oa(a.c)===null)){let a=[];for(let A of EN9w)a[A.i]=A.y;return a}}return null}",
    "function e8(t){let e=[];for(let i of t.rows){let s=[],EN9w=[],n=[];for(let a of i.cells){let A=/^(19|20)\\d{2}$/.test(a.text),r=A?parseInt(a.text,10):EN9_HY(a.text);A?s.push({year:r,x0:a.x0,x1:a.x1,b:1}):r!==null?s.push({year:r,x0:a.x0,x1:a.x1,b:0}):EN9_CYW.test(a.text.trim())?EN9w.push({year:-1,x0:a.x0,x1:a.x1}):EN9_PYW.test(a.text.trim())?EN9w.push({year:-2,x0:a.x0,x1:a.x1}):n.push(a)}let EN9g=!(n.length>1||n.some(a=>a.text.length>14||Oa(a.text)!==null));s.length>=1&&s.length<=4&&!EN9w.length&&EN9g&&(s.every(a=>a.b)||s.length>=2)?e.push({page:i.page,y:i.y,cols:s.map(a=>({year:a.year,x0:a.x0,x1:a.x1}))}):!s.length&&EN9w.length===2&&EN9w.some(a=>a.year===-1)&&EN9w.some(a=>a.year===-2)&&EN9g&&e.push({page:i.page,y:i.y,cols:EN9w.map(a=>({year:a.year,x0:a.x0,x1:a.x1}))})}return e}",
    "function q1(t,e,i){let s=[],n=new Map;for(let A of e)n.has(A.page)||n.set(A.page,[]),n.get(A.page).push(A);let a=(A,r)=>{let o=(n.get(A)||[]).filter(c=>c.y>r);if(o.length)return o.reduce((c,g)=>c.y<g.y?c:g);let l=i?.inheritRulerFrom?.get(A);if(l!==void 0){let c=n.get(l)||[];if(c.length)return c[c.length-1]}return null};for(let A of t.rows){if(i?.pages&&!i.pages.has(A.page))continue;let r=null,o=-1,l=[];for(let f=0;f<A.cells.length;f++){let C=A.cells[f],I=Oa(C.text);I!==null?l.push({v:I,x0:C.x0,x1:C.x1,idx:f}):r===null&&$w(C.text)&&C.text.trim().length>2&&(r=C.text.trim(),o=f)}if(!r)continue;let c=l.filter(f=>f.idx>o);if(!c.length){if(typeof EN9SECTB<\"u\"&&!(i&&i.raw)&&r.length<=40&&EN9SECTB.some(EN9z=>EN9z[0].test(r)))s.push({label:r,values:[],years:null,page:A.page,x0:A.cells&&A.cells[0]&&typeof A.cells[0].x0==\"number\"?A.cells[0].x0:void 0,EN9banner:!0});continue}if(c.length>=2&&c.every(f=>/^(19|20)\\d{2}$/.test(A.cells[f.idx].text.trim())))continue;let g=a(A.page,A.y),h;if(g){let f=g.cols.map(Q=>t.approxWidths?Q.x0:Q.x1).sort((Q,p)=>Q-p),C=f.slice(1).map((Q,p)=>Q-f[p]),I=C.length?C.sort((Q,p)=>Q-p)[Math.floor(C.length/2)]:0,B=t.approxWidths?40:Math.max(24,I*.45),E=new Map;h=c.map(()=>null),c.forEach((Q,p)=>{let y=-1,m=1/0;if(g.cols.forEach((w,S)=>{let b=t.approxWidths?Math.abs(Q.x0-w.x0):Math.abs(Q.x1-w.x1);b<m&&(m=b,y=S)}),y>=0&&m<=B){let w=E.get(y);(!w||m<w.dist)&&(w&&(h[w.slot]=null),E.set(y,{dist:m,slot:p}),h[p]=g.cols[y].year)}})}let u={label:r,values:c.map(f=>f.v),years:h,page:A.page,x0:A.cells&&A.cells[0]&&typeof A.cells[0].x0==\"number\"?A.cells[0].x0:void 0};if(i?.raw){s.push(u);continue}let d=Yv(u);d&&s.push(d)}return s}"
  ],
};
